#100MHz
set_property PACKAGE_PIN W5 [get_ports sysclk]
set_property IOSTANDARD LVCMOS33 [get_ports sysclk]
create_clock -name clk -period 10.000 [get_ports sysclk]

set_property PACKAGE_PIN T18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN U17 [get_ports button]
set_property IOSTANDARD LVCMOS33 [get_ports button]

#led 0-7
set_property PACKAGE_PIN U16 [get_ports leds[0]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[0]]
set_property PACKAGE_PIN E19 [get_ports leds[1]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[1]]
set_property PACKAGE_PIN U19 [get_ports leds[2]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[2]]
set_property PACKAGE_PIN V19 [get_ports leds[3]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[3]]
set_property PACKAGE_PIN W18 [get_ports leds[4]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[4]]
set_property PACKAGE_PIN U15 [get_ports leds[5]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[5]]
set_property PACKAGE_PIN U14 [get_ports leds[6]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[6]]
set_property PACKAGE_PIN V14 [get_ports leds[7]]
set_property IOSTANDARD LVCMOS33 [get_ports leds[7]]

set_property PACKAGE_PIN U2 [get_ports {digi[8]}]
set_property PACKAGE_PIN U4 [get_ports {digi[9]}]
set_property PACKAGE_PIN V4 [get_ports {digi[10]}]
set_property PACKAGE_PIN W4 [get_ports {digi[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[11]}]
#CA->CG
set_property PACKAGE_PIN W7 [get_ports {digi[0]}]
set_property PACKAGE_PIN W6 [get_ports {digi[1]}]
set_property PACKAGE_PIN U8 [get_ports {digi[2]}]
set_property PACKAGE_PIN V8 [get_ports {digi[3]}]
set_property PACKAGE_PIN U5 [get_ports {digi[4]}]
set_property PACKAGE_PIN V5 [get_ports {digi[5]}]
set_property PACKAGE_PIN U7 [get_ports {digi[6]}]
set_property PACKAGE_PIN V7 [get_ports {digi[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digi[0]}]

set_property PACKAGE_PIN V16 [get_ports selreg[0]]
set_property IOSTANDARD LVCMOS33 [get_ports selreg[0]]
set_property PACKAGE_PIN W16 [get_ports selreg[1]]
set_property IOSTANDARD LVCMOS33 [get_ports selreg[1]]
set_property PACKAGE_PIN W17 [get_ports selreg[2]]
set_property IOSTANDARD LVCMOS33 [get_ports selreg[2]]
set_property PACKAGE_PIN W15 [get_ports selreg[3]]
set_property IOSTANDARD LVCMOS33 [get_ports selreg[3]]
set_property PACKAGE_PIN V15 [get_ports selreg[4]]
set_property IOSTANDARD LVCMOS33 [get_ports selreg[4]]
set_property PACKAGE_PIN W14 [get_ports selreg[5]]
set_property IOSTANDARD LVCMOS33 [get_ports selreg[5]]
set_property PACKAGE_PIN W13 [get_ports selreg[6]]
set_property IOSTANDARD LVCMOS33 [get_ports selreg[6]]
set_property PACKAGE_PIN V17 [get_ports selclk]
set_property IOSTANDARD LVCMOS33 [get_ports selclk]
